collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5089605
color:
  saturation: 0.9522374
  brandStrength: 0.8333333
  lightness: 0.8635216
  brandColors:
    - '#FFFFFF'
    - '#150001'
    - '#47321F'
    - '#FFB864'
    - '#95B1BF'
  rhythmicContrast: 0.9328369
layout_spectrum: 0.9946237
name: Kent Sammons II
